# https://raw.githubusercontent.com/dracula/alacritty/master/dracula.yml
colors:
  primary:
    background: "#282a36"
    foreground: "#f8f8f2"
    bright_foreground: "#ffffff"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"
  footer_bar:
    background: "#282a36"
    foreground: "#f8f8f2"
  hints:
    start:
      foreground: "#282a36"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#282a36"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: "#44475a"
  normal:
    black: "#21222c"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#bd93f9"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#f8f8f2"
  bright:
    black: "#6272a4"
    red: "#ff6e6e"
    green: "#69ff94"
    yellow: "#ffffa5"
    blue: "#d6acff"
    magenta: "#ff92df"
    cyan: "#a4ffff"
    white: "#ffffff"
font:
  size: 13.0
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
key_bindings:
  - { key: L, mods: Alt|Shift, chars: "|" }
  - { key: Key5, mods: Alt, chars: "{" }
  - { key: Minus, mods: Alt, chars: "}" }
  - { key: Key5, mods: Alt|Shift, chars: "[" }
  - { key: Minus, mods: Alt|Shift, chars: "]" }
  - { key: Return, mods: Command, action: ToggleFullscreen }
live_config_reload: true
window:
  startup_mode: Maximized
  decorations: buttonless
  dynamic_padding: true
  option_as_alt: OnlyLeft
  padding:
    x: 5
    y: 5
