font:
  size: 13.0
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
key_bindings:
  - { key: L, mods: Alt|Shift, chars: "|" }
  - { key: Key5, mods: Alt, chars: "{" }
  - { key: Minus, mods: Alt, chars: "}" }
  - { key: Key5, mods: Alt|Shift, chars: "[" }
  - { key: Minus, mods: Alt|Shift, chars: "]" }
  - { key: Return, mods: Command, action: ToggleFullscreen }
live_config_reload: true
window:
  startup_mode: Maximized
  decorations: buttonless
  dynamic_padding: true
  option_as_alt: None
  padding:
    x: 5
    y: 5
