alt_send_esc: false
# https://raw.githubusercontent.com/arcticicestudio/nord-alacritty/main/src/nord.yml
colors:
  primary:
    background: "#2e3440"
    foreground: "#d8dee9"
    dim_foreground: "#a5abb6"
  cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  vi_mode_cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  selection:
    text: CellForeground
    background: "#4c566a"
  search:
    matches:
      foreground: CellBackground
      background: "#88c0d0"
    bar:
      background: "#434c5e"
      foreground: "#d8dee9"
  normal:
    black: "#3b4252"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#88c0d0"
    white: "#e5e9f0"
  bright:
    black: "#4c566a"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#8fbcbb"
    white: "#eceff4"
  dim:
    black: "#373e4d"
    red: "#94545d"
    green: "#809575"
    yellow: "#b29e75"
    blue: "#68809a"
    magenta: "#8c738c"
    cyan: "#6d96a5"
    white: "#aeb3bb"
font:
  size: 13.0
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
key_bindings:
  - { key: L, mods: Alt|Shift, chars: "|" }
  - { key: Key5, mods: Alt, chars: "{" }
  - { key: Minus, mods: Alt, chars: "}" }
  - { key: Key5, mods: Alt|Shift, chars: "[" }
  - { key: Minus, mods: Alt|Shift, chars: "]" }
  - { key: Return, mods: Command, action: ToggleFullscreen }
live_config_reload: true
window:
  startup_mode: Maximized
  decorations: buttonless
  dynamic_padding: true
  padding:
    x: 5
    y: 5
