font:
  size: 13.0
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
live_config_reload: true
window:
  startup_mode: Maximized
  decorations: buttonless
  dynamic_padding: true
  padding:
    x: 0
    y: 10
