#!/usr/bin/env bash

if ! which xcode-select >/dev/null; then
  echo 'CAN I HAZ XCODE ?'
  exec xcode-select --install
  exit 1
fi

if ! which stow >/dev/null; then
  echo 'CAN I HAZ STOW ?'
  exit 1
fi

script_name=$(basename "$0")

stow -S . -t "$HOME" -v \
  --ignore='README.md' \
  --ignore="LICENCE" \
  --ignore="$script_name" && \
  exec "$SHELL"

./.brew 2>/dev/null

./.osx
