add_newline = true

[character]
symbol = "$"
use_symbol_for_status = false

[docker]
symbol = " "

[git_branch]
symbol = " "

[line_break]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[nix_shell]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false

[memory_usage]
disabled = true
show_percentage = true
show_swap = false
symbol = " "
threshold = 85
separator = "/"
style = "bold dimmed red"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"
