# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

palette = "everforest"

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[\\$](bold #ff5555)"
success_symbol = "[\\$](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[docker_context]
symbol = " "

[git_branch]
style = "bold #ff79c6"
symbol = " "

[git_status]
style = "bold #ff5555"

[line_break]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[hostname]
style = "bold #bd93f9"

[nodejs]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[nix_shell]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false
contexts = [
  { context_pattern = "*-prd", style = "bold red", symbol = "⚠️  DANGER ⚠️  " }
]

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[vagrant]
disabled = true

[memory_usage]
disabled = true
show_percentage = true
show_swap = false
symbol = " "
threshold = 85
separator = "/"
style = "bold dimmed red"

[battery]
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[palettes.everforest]
bg_dim = "#232a2e"
bg0 = "#2d353b"
bg1 = "#343f44"
bg2 = "#3d484d"
bg3 = "#475258"
bg4 = "#4f585e"
bg5 = "#56635f"
bg_visual = "#543a48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3a515d"
bg_yellow = "#4d4c43"
fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"
