add_newline = true

[character]
symbol = "$"
use_symbol_for_status = false

[line_break]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[nix_shell]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = 85
separator = "/"
style = "bold dimmed red"

[battery]
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"
