# https://starship.rs/config/
# https://github.com/dracula/starship/blob/master/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[\\$](bold #ff5555)"
success_symbol = "[\\$](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[docker_context]
symbol = " "

[git_branch]
style = "bold #ff79c6"
symbol = " "

[git_status]
style = "bold #ff5555"

[line_break]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[hostname]
style = "bold #bd93f9"

[nodejs]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[nix_shell]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false
contexts = [
  { context_pattern = "*-prd", style = "bold red", symbol = "⚠️  DANGER ⚠️  " }
]

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[vagrant]
disabled = true

[memory_usage]
disabled = true
show_percentage = true
show_swap = false
symbol = " "
threshold = 85
separator = "/"
style = "bold dimmed red"

[battery]
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"
