add_newline = true

[character]
symbol = "$"
use_symbol_for_status = false

[line_break]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[nix_shell]
disabled = true

[java]
disabled = true
