# https://starship.rs/config/

palette = "catppuccin_latte"

add_newline = true

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[\\$](bold green)"
success_symbol = "[\\$](bold red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold lavender"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[line_break]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[nix_shell]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false

[username]
format = "[$user]($style) on "

[vagrant]
disabled = true

[memory_usage]
disabled = true
show_percentage = true
show_swap = false
symbol = " "
threshold = 85
separator = "/"
style = "bold dimmed red"

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"


# https://raw.githubusercontent.com/catppuccin/starship/main/palettes/latte.toml
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
