#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

OS="$(uname)"
[[ $OS != 'Darwin' ]] && exit 0

echo '--> configure dnsmasq'

mkdir -p "$HOME/.dnsmasq.d"
cat <<EOT > /usr/local/etc/dnsmasq.conf
# https://github.com/drduh/OS-X-Security-and-Privacy-Guide#dnsmasq

# Forward queries to dnscrypt on localhost
server=127.0.0.1#5355

# Uncomment to forward queries to Google Public DNS
#server=8.8.8.8

# Never forward plain names
domain-needed

# Blackhole Tor hidden services and local TLDs
address=/.onion/0.0.0.0
address=/.local/0.0.0.0
address=/.mycoolnetwork/0.0.0.0

# Never forward addresses in the non-routed address spaces
bogus-priv

# Reject private addresses from upstream nameservers
stop-dns-rebind

# Query servers in order
strict-order

# Set the size of the cache
# The default is to keep 150 hostnames
cache-size=8192

# Optional logging directives
log-async
log-dhcp
log-facility=/var/log/dnsmasq.log

# Uncomment to log all queries
#log-queries

# Uncomment to enable DNSSEC
#dnssec
#trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
#dnssec-check-unsigned

# user
user=$USER

# Include localconfig
conf-dir=$HOME/.dnsmasq.d/
EOT

# Configure dnscrypt
cat <<EOT > /usr/local/opt/dnscrypt-proxy/homebrew.mxcl.dnscrypt-proxy.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-/Apple/DTD PLIST 1.0/EN" "http:/www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.dnscrypt-proxy</string>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy</string>
      <string>--ephemeral-keys</string>
      <string>--resolvers-list=/usr/local/opt/dnscrypt-proxy/share/dnscrypt-proxy/dnscrypt-resolvers.csv</string>
      <string>--resolver-name=dnscrypt.org-fr</string>
      <string>--local-address=127.0.0.1:5355</string>
    </array>
    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
  </dict>
</plist>
EOT

# Update dnscrypt resolvers
dnscrypt-update-resolvers

# Start services
brew services restart dnscrypt-proxy
sudo brew services restart dnsmasq

# Configure dns to use localhost
networksetup -listallnetworkservices | while read -r interface; do
  if [[ "$interface" == "*Ethernet" ]] \
    || [[ "$interface" == "Thunderbolt Ethernet" ]] \
    || [[ "$interface" == "Wi-Fi" ]]; then
    sudo networksetup -setdnsservers "$interface" 127.0.0.1
  fi
done
