#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

OS="$(uname)"
[[ $OS != 'Darwin' ]] && exit 0

# remove dnsmasq
brew uninstall --force dnsmasq || true

# Consolidate my /etc/hosts too just in case I don't use my DNS, eg: automatic
# network profile
su admin -c "curl -s 'https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts' \
  | sudo tee '/etc/hosts'"

# cleanup old dnscrypt-proxy 1.9.x configs
rm -vf "$(brew --prefix)/opt/dnscrypt-proxy/homebrew.mxcl.dnscrypt-proxy.*.plist"

# Configure dnscrypt
cat <<DNSCRYPT-PROXY > "$(brew --prefix)/etc/dnscrypt-proxy.toml"
block_ipv6 = false
cache = true
cache_max_ttl = 86400
cache_min_ttl = 600
cache_neg_ttl = 60
cache_size = 16000
cert_refresh_delay = 30
cloaking_rules = "$(brew --prefix)/etc/dnscrypt-proxy-cloaking-rules.txt"
daemonize = false
dnscrypt_servers = true
doh_servers = true
fallback_resolver = '9.9.9.9:53'
force_tcp = false
ignore_system_dns = true
ipv4_servers = true
ipv6_servers = false
lb_strategy = 'p2'
listen_addresses = ['127.0.0.1:53', '[::1]:53']
max_clients = 100
require_dnssec = false
require_nofilter = true
require_nolog = true
timeout = 3000
[query_log]
  file = "/dev/null"
  format = "tsv"
[blacklist]
  blacklist_file = '$(brew --prefix)/etc/dnscrypt-proxy-blacklist.txt'
  log_file = '/dev/null'
[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/tmp/public-resolvers.md'
  format = 'v2'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
[schedules]
  [schedules.'time-to-sleep']
  mon = [{after='23:00', before='7:00'}]
  tue = [{after='23:00', before='7:00'}]
  wed = [{after='23:00', before='7:00'}]
  thu = [{after='23:00', before='7:00'}]
  fri = [{after='00:00', before='7:00'}]
  sat = [{after='00:00', before='7:00'}]
  sun = [{after='23:00', before='7:00'}]
  [schedules.'work']
  mon = [{after='9:00', before='18:00'}]
  tue = [{after='9:00', before='18:00'}]
  wed = [{after='9:00', before='18:00'}]
  thu = [{after='9:00', before='18:00'}]
  fri = [{after='9:00', before='17:00'}]
DNSCRYPT-PROXY

pushd "$(brew --prefix)/etc/"
	touch dnscrypt-proxy-cloaking-rules.txt
  wget https://raw.githubusercontent.com/bdossantos/bds.home/master/files/etc/dnscrypt-proxy/domains-blacklist-local-additions.txt
  wget https://raw.githubusercontent.com/bdossantos/bds.home/master/files/etc/dnscrypt-proxy/domains-blacklist.conf
  wget https://raw.githubusercontent.com/bdossantos/bds.home/master/files/etc/dnscrypt-proxy/domains-time-restricted.txt
  wget https://raw.githubusercontent.com/bdossantos/bds.home/master/files/etc/dnscrypt-proxy/domains-whitelist.txt

  # YOLO!
  python <(curl -Ss https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/25f1de385b50f45032f386aa31c131bbb168f00e/utils/generate-domains-blacklists/generate-domains-blacklist.py) --timeout 60 \
  > dnscrypt-proxy-blacklist.txt.tmp

  mv -f dnscrypt-proxy-blacklist.txt.tmp dnscrypt-proxy-blacklist.txt
popd

cat <<EOT > "$(brew --prefix)/opt/dnscrypt-proxy/homebrew.mxcl.dnscrypt-proxy.plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-/Apple/DTD PLIST 1.0/EN" "http:/www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.dnscrypt-proxy</string>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>ProgramArguments</key>
    <array>
      <string>$(brew --prefix)/opt/dnscrypt-proxy/sbin/dnscrypt-proxy</string>
      <string>-config</string>
      <string>$(brew --prefix)/etc/dnscrypt-proxy.toml</string>
    </array>
    <key>UserName</key>
    <string>root</string>
    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
  </dict>
</plist>
EOT

su admin -c "
sudo ${HOME}/.homebrew/bin/brew services restart dnscrypt-proxy
sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder
"
