#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

echo '--> setup privoxy'

cat <<EOT > "$(brew --prefix)/etc/privoxy/user.action"
{ +block{social networking} }
www.facebook.com/(extern|plugins)/(login_status|like(box)?|activity|fan)\.php
#.facebook.com

{ +block{unwanted images} +handle-as-image }
.com/ads/
/.*1x1.gif
/.*fb-icon.[jpg|gif|png]
/assets/social-.*
/cleardot.gif
/img/social.*
ads.*.co.*/
ads.*.com/

{ +redirect{s@http://@https://@} }
.google.com
.wikipedia.org
code.jquery.com
imgur.com
EOT

brew services restart privoxy
while ! true | nc 127.0.0.1 8118 >/dev/null; do sleep 2; done

ALL_PROXY=127.0.0.1:8118 curl -s -I http://p.p/
ALL_PROXY=127.0.0.1:8118 curl -s -I -L ads.foo.com/ \
	| grep -q '403 Request blocked by Privoxy'
ALL_PROXY=127.0.0.1:8118 curl -s -I -L imgur.com/ \
	| grep -q '302 Local Redirect from Privoxy'
