#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

cat <<EOT > "$(brew --prefix)/etc/tor/torrc"
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
AvoidDiskWrites 1
ControlPort 9051
ClientOnly 1
DNSPort 127.0.0.1:9053
HardwareAccel 1
Log notice syslog
NumCPUs 4
SafeLogging 1
SocksPort 9050
SocksBindAddress 127.0.0.1
FascistFirewall 1
ReachableAddresses *:80,*:443

# See: https://bridges.torproject.org/
#UseBridges 1
#Bridge [transport] IP:ORPort [fingerprint]
EOT

brew services restart tor
while ! true | nc 127.0.0.1 9050 >/dev/null; do sleep 2; done

# check if Tor is Up & Running
tor-resolve bds.io >/dev/null
tor-resolve -x 8.8.8.8 >/dev/null

torsocks wget -q -O - https://check.torproject.org/ \
  | grep 'Congratulations. This browser is configured to use Tor.'
