# https://raw.githubusercontent.com/dracula/spotify-tui/master/dracula.yml
theme:
  active: "139,233,253" # current playing song in list
  banner: "80,250,123" # the "spotify-tui" banner on launch
  error_border: "241,250,140" # error dialog border
  error_text:
    "248,248,242" # error message text (e.g. "Spotify API
    # reported error 404")
  hint: "241,250,140" # hint text in errors
  hovered: "255,184,108" # hovered pane border
  inactive: "248,248,242" # borders of inactive panes
  playbar_background: "68,71,90" # background of progress bar
  playbar_progress: "248,248,242" # filled-in part of the progress bar
  playbar_progress_text:
    "248,248,242" # song length and time played/left
    # indicator in the progress bar
  playbar_text: "248,248,242" # artist name in player pane
  selected:
    "80,250,123" # a) selected pane border, b) hovered item
    # in list, & c) track title in player
  text: "248,248,242" # text in panes
  header:
    "248,248,242" # header text in panes (e.g. 'Title',
    # 'Artist', etc.)

behavior:
  enable_text_emphasis: true
  enforce_wide_search_bar: false
  liked_icon: ♥
  paused_icon: ⏸
  playing_icon: ▶
  repeat_context_icon: 🔁
  repeat_track_icon: 🔂
  seek_milliseconds: 5000
  set_window_title: true
  show_loading_indicator: true
  shuffle_icon: 🔀
  tick_rate_milliseconds: 250
  volume_increment: 10

keybindings:
  add_item_to_queue: "z"
  audio_analysis: "v"
  back: "ctrl-q"
  basic_view: "B"
  copy_album_url: "C"
  copy_song_url: "c"
  decrease_volume: "-"
  help: "?"
  increase_volume: "+"
  jump_to_album: "a"
  jump_to_artist_album: "A"
  jump_to_context: "o"
  manage_devices: "d"
  next_track: "n"
  previous_track: "p"
  repeat: "r"
  search: "/"
  seek_backwards: "<"
  seek_forwards: ">"
  shuffle: "ctrl-s"
  toggle_playback: " "
