# Runtimes required for the Neovim setup
# https://mise.jdx.dev/configuration.html
[settings]
idiomatic_version_file_enable_tools = ["ruby", "python", "node"]

[tools]
node = "22"
lua = "5.4"
python = "3.13"
ruby = "3.3"
